general {
  hide_cursor = true
  border_size = 2
  gaps_in = 2
  gaps_out = 2

}

animations {
  enabled = false
}

background {
  monitor =
  path = $HOME/Pictures/Wallpaper/astronaut.jpg
}

input-field {
  monitor =
  font_family = JetBrainsMono Nerd Font
  size = 500, 20
  hide_input = false
  placeholder_text = Acerte se for capaz!
}

image {
  path = $HOME/.config/hypr/lock/doctor_stone.jpg
  size = 150
  rounding = 10

  position = 0 80%
  halign = right
  valign = top
}
